env:
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  localStorage: true
  sessionStorage: true
  window: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}
